let level1;

function initLevel() {
  level1 = new Level(
    [new Enemie(), new Enemie(), new Enemie(), new Enemie(), new Endboss()],
    [new Cloud(), new Cloud(), new Cloud(), new Cloud(), new Cloud()],
    [new Ammo(), new Ammo(), new Ammo(), new Ammo(), new Ammo()],
    [new Coin(), new Coin(), new Coin(), new Coin(), new Coin()],
    [
      new BackgroundObject("img/object_bg/sky.png", -1280),
      new BackgroundObject("img/object_bg/houses.png", -1280),
      new BackgroundObject("img/object_bg/houses2.png", -1280),
      new BackgroundObject("img/object_bg/houses1.png", -1280),
      new BackgroundObject("img/object_bg/fountain&bush.png", -1280),
      new BackgroundObject("img/object_bg/umbrella&policebox.png", -1280),
      new BackgroundObject("img/object_bg/road.png", -1280),
      new BackgroundObject("img/object_bg/sky.png", 0),
      new BackgroundObject("img/object_bg/houses.png", 0),
      new BackgroundObject("img/object_bg/houses2.png", 0),
      new BackgroundObject("img/object_bg/houses1.png", 0),
      new BackgroundObject("img/object_bg/fountain&bush.png", 0),
      new BackgroundObject("img/object_bg/umbrella&policebox.png", 0),
      new BackgroundObject("img/object_bg/road.png", 0),
      new BackgroundObject("img/object_bg/sky.png", 1280),
      new BackgroundObject("img/object_bg/houses.png", 1280),
      new BackgroundObject("img/object_bg/houses2.png", 1280),
      new BackgroundObject("img/object_bg/houses1.png", 1280),
      new BackgroundObject("img/object_bg/fountain&bush.png", 1280),
      new BackgroundObject("img/object_bg/umbrella&policebox.png", 1280),
      new BackgroundObject("img/object_bg/road.png", 1280),
      new BackgroundObject("img/object_bg/sky.png", 2560),
      new BackgroundObject("img/object_bg/houses.png", 2560),
      new BackgroundObject("img/object_bg/houses2.png", 2560),
      new BackgroundObject("img/object_bg/houses1.png", 2560),
      new BackgroundObject("img/object_bg/fountain&bush.png", 2560),
      new BackgroundObject("img/object_bg/umbrella&policebox.png", 2560),
      new BackgroundObject("img/object_bg/road.png", 2560),
      new BackgroundObject("img/object_bg/sky.png", 3840),
      new BackgroundObject("img/object_bg/houses.png", 3840),
      new BackgroundObject("img/object_bg/houses2.png", 3840),
      new BackgroundObject("img/object_bg/houses1.png", 3840),
      new BackgroundObject("img/object_bg/fountain&bush.png", 3840),
      new BackgroundObject("img/object_bg/umbrella&policebox.png", 3840),
      new BackgroundObject("img/object_bg/road.png", 3840),
    ]
  );
}
